FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

COPY alembic.ini .
COPY migrations ./migrations
COPY configs ./configs
COPY src ./src
